sonar.projectKey=git-detective
sonar.projectName=Git Detective
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.modules=backend,frontend

backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main/java
backend.sonar.tests=src/test/java
backend.sonar.java.binaries=target/classes
backend.sonar.java.test.binaries=target/test-classes

frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/.next/**,**/components/ui/**
